import { productCategories } from '@/schema/catalogs'
import { asNumber, roundCurrency, warehouseStockStatus } from '@/schema/formulas'
import { defineTable, migrationRef } from '@/schema/helpers'

export const almacenTable = defineTable({
  name: 'ALMACEN',
  sheet: 'ALMACEN',
  label: 'ID PRODUCTO',
  legacyBusinessKey: 'ID PRODUCTO',
  permissionView: 'Almacen',
  module: 'Inventario',
  icon: 'Package',
  description: 'Catálogo maestro de productos y existencias.',
  defaultView: 'table',
  columns: [
    migrationRef('proveedor_uuid', 'Proveedor interno', 'PROVEEDORES'),
    {
      name: 'No. Item',
      type: 'Number',
      required: true,
      readOnly: true,
      description: 'Consecutivo asignado automáticamente por el servidor.',
    },
    { name: 'ID PRODUCTO', type: 'Text', labelColumn: true, required: true },
    { name: 'IMAGEN', type: 'Image', required: true },
    {
      name: 'PROVEEDOR',
      type: 'Text',
      description: 'Marca o fabricante del dispositivo GPS.',
    },
    { name: 'NOMBRE', type: 'Text' },
    { name: 'UNIDAD DE MEDIDA', type: 'Text', hidden: true },
    { name: 'UNIDAD DE MEDIDA SAT', type: 'Text', hidden: true },
    { name: 'KIT INSTALACION', type: 'Price', hidden: true },
    { name: 'MONEDA', type: 'Text', hidden: true },
    { name: 'TIPO DE CAMBIO', type: 'Price', hidden: true },
    { name: 'COSTO', type: 'Price', hidden: true },
    { name: 'MANO DE OBRA', type: 'Price', hidden: true },
    {
      name: 'PRECIO VENTA PARA ASESOR',
      type: 'Price',
      hidden: true,
      readOnly: true,
      formula: (row) => roundCurrency(asNumber(row['COSTO']) * 1.16),
    },
    { name: 'STOCK MINIMO', type: 'Number' },
    { name: 'STOCK MAXIMO', type: 'Number' },
    { name: 'AVISO DE COMPRA', type: 'Text', readOnly: true },
    { name: 'MTS. CABLE INCLUIDOS', type: 'Text', hidden: true },
    { name: 'CATEGORIA', type: 'Enum', values: productCategories, required: true },
    { name: 'CRITICO', type: 'Text', hidden: true },
    { name: 'CENTRO DE COSTOS', type: 'Text', hidden: true },
    { name: 'TIEMPO DE ENTREGA', type: 'Text', hidden: true },
    { name: 'CLAVE SAT', type: 'Text', hidden: true },
    {
      name: 'ESTATUS',
      type: 'Text',
      readOnly: true,
      description: 'Calculado automaticamente con el stock minimo, maximo y actual.',
      formula: (row) => warehouseStockStatus(
        row.STOCK,
        row['STOCK MINIMO'],
        row['STOCK MAXIMO'],
      ),
    },
    {
      name: 'COMPRAS',
      type: 'Number',
      readOnly: true,
      description: 'Numero acumulado de operaciones de compra registradas.',
    },
    {
      name: 'PEDIDOS',
      label: 'SALIDAS',
      type: 'Number',
      readOnly: true,
      description: 'Total acumulado de unidades con salida aprobada.',
    },
    { name: 'STOCK', type: 'Number', readOnly: true },
    {
      name: 'Related PEDIDOSs',
      type: 'List',
      virtual: true,
      readOnly: true,
      ref: { table: 'PEDIDOS', keyColumn: 'producto_uuid' },
    },
    {
      name: 'Related COMPRASs',
      type: 'List',
      virtual: true,
      readOnly: true,
      ref: { table: 'COMPRAS', keyColumn: 'producto_uuid' },
    },
    { name: 'SVG', type: 'Show', virtual: true, readOnly: true },
  ],
})
