import { productCategories } from '@/schema/catalogs'
import { asNumber, roundCurrency } from '@/schema/formulas'
import { defineTable, migrationRef } from '@/schema/helpers'

export const almacenTable = defineTable({
  name: 'ALMACEN',
  sheet: 'ALMACEN',
  label: 'ID PRODUCTO',
  legacyBusinessKey: 'ID PRODUCTO',
  permissionView: 'Almacen',
  module: 'Inventario',
  icon: 'Package',
  description: 'Catálogo maestro de productos y existencias.',
  defaultView: 'table',
  columns: [
    migrationRef('proveedor_uuid', 'Proveedor interno', 'PROVEEDORES'),
    { name: 'No. Item', type: 'Number', required: true },
    { name: 'ID PRODUCTO', type: 'Text', labelColumn: true, required: true },
    { name: 'IMAGEN', type: 'Image', required: true },
    {
      name: 'PROVEEDOR',
      type: 'Ref',
      ref: { table: 'PROVEEDORES', keyColumn: '_uuid' },
      syncTo: 'proveedor_uuid',
    },
    { name: 'NOMBRE', type: 'Text' },
    { name: 'UNIDAD DE MEDIDA', type: 'Text', hidden: true },
    { name: 'UNIDAD DE MEDIDA SAT', type: 'Text', hidden: true },
    { name: 'KIT INSTALACION', type: 'Price', hidden: true },
    { name: 'MONEDA', type: 'Text', hidden: true },
    { name: 'TIPO DE CAMBIO', type: 'Price', hidden: true },
    { name: 'COSTO', type: 'Price', hidden: true },
    { name: 'MANO DE OBRA', type: 'Price', hidden: true },
    {
      name: 'PRECIO VENTA PARA ASESOR',
      type: 'Price',
      hidden: true,
      readOnly: true,
      formula: (row) => roundCurrency(asNumber(row['COSTO']) * 1.16),
    },
    { name: 'STOCK MINIMO', type: 'Number' },
    { name: 'STOCK MAXIMO', type: 'Number' },
    { name: 'AVISO DE COMPRA', type: 'Text', readOnly: true },
    { name: 'MTS. CABLE INCLUIDOS', type: 'Text', hidden: true },
    { name: 'CATEGORIA', type: 'Enum', values: productCategories },
    { name: 'CRITICO', type: 'Text', hidden: true },
    { name: 'CENTRO DE COSTOS', type: 'Text', hidden: true },
    { name: 'TIEMPO DE ENTREGA', type: 'Text', hidden: true },
    { name: 'CLAVE SAT', type: 'Text', hidden: true },
    { name: 'ESTATUS', type: 'Text' },
    { name: 'COMPRAS', type: 'Ref', ref: { table: 'COMPRAS', keyColumn: '_uuid' } },
    { name: 'PEDIDOS', type: 'Ref', ref: { table: 'PEDIDOS', keyColumn: '_uuid' } },
    { name: 'STOCK', type: 'Number', readOnly: true },
    {
      name: 'Related PEDIDOSs',
      type: 'List',
      virtual: true,
      readOnly: true,
      ref: { table: 'PEDIDOS', keyColumn: 'producto_uuid' },
    },
    {
      name: 'Related COMPRASs',
      type: 'List',
      virtual: true,
      readOnly: true,
      ref: { table: 'COMPRAS', keyColumn: 'producto_uuid' },
    },
    { name: 'SVG', type: 'Show', virtual: true, readOnly: true },
  ],
})
