import {
  crmContactOrigins,
  crmContactTypes,
  crmResponsibles,
} from '@/schema/catalogs'
import { defineTable, migrationRef } from '@/schema/helpers'

export const gestionClientesTable = defineTable({
  name: 'Gestion Clientes',
  displayName: 'Seguimiento Clientes',
  sheet: 'Gestion Clientes',
  label: 'ID_CRM',
  legacyBusinessKey: 'ID_CRM',
  permissionView: 'Gestion Clientes',
  module: 'CRM',
  icon: 'Handshake',
  description: 'Directorio profesional de contactos y seguimiento comercial.',
  defaultView: 'dashboard',
  columns: [
    migrationRef('cliente_uuid', 'Cliente interno', 'CLIENTES'),
    {
      name: 'ID_CRM',
      type: 'Text',
      labelColumn: true,
      required: true,
      readOnly: true,
      section: 'Información profesional',
      description: 'Consecutivo automático con formato GC-0001.',
    },
    { name: 'Nombre', label: 'NOMBRE', type: 'Name', required: true, section: 'Información profesional' },
    { name: 'Cargo', label: 'CARGO', type: 'Text', section: 'Información profesional' },
    { name: 'NOMBRE_EMPRESA', type: 'Text', required: true, section: 'Información profesional' },
    {
      name: 'Tipo de Contacto',
      label: 'TIPO DE CONTACTO',
      type: 'Enum',
      required: true,
      values: crmContactTypes,
      section: 'Información profesional',
      defaultValue: () => 'Prospecto',
    },
    {
      name: 'Responsable',
      label: 'RESPONSABLE',
      type: 'EnumList',
      required: true,
      values: crmResponsibles,
      section: 'Información profesional',
      description: 'Selecciona uno o varios responsables del contacto.',
    },
    { name: 'Teléfono del trabajo', label: 'TELÉFONO DEL TRABAJO', type: 'Phone', section: 'Datos de contacto' },
    { name: 'Móvil', label: 'MÓVIL', type: 'Phone', section: 'Datos de contacto' },
    { name: 'Otro número de teléfono', label: 'OTRO NÚMERO DE TELÉFONO', type: 'Phone', section: 'Datos de contacto' },
    { name: 'Sitio web Corporativo', label: 'SITIO WEB CORPORATIVO', type: 'Url', section: 'Datos de contacto' },
    { name: 'E-mail del trabajo', label: 'E-MAIL DEL TRABAJO', type: 'Email', section: 'Datos de contacto' },
    { name: 'Última actualización en', label: 'ÚLTIMA ACTUALIZACIÓN EN', type: 'DateTime', readOnly: true, section: 'Auditoría' },
    {
      name: 'Origen',
      label: 'ORIGEN',
      type: 'Enum',
      values: crmContactOrigins,
      section: 'Procedencia',
      defaultValue: () => 'Prospección',
    },
    { name: 'Información de origen', label: 'INFORMACIÓN DE ORIGEN', type: 'Text', section: 'Procedencia' },
    { name: 'Creado por', label: 'CREADO POR', type: 'Text', readOnly: true, section: 'Auditoría' },
    { name: 'Creado', label: 'CREADO', type: 'DateTime', readOnly: true, section: 'Auditoría' },
    { name: 'Modificado por', label: 'MODIFICADO POR', type: 'Text', readOnly: true, section: 'Auditoría' },
    { name: 'Modificado', label: 'MODIFICADO', type: 'DateTime', readOnly: true, section: 'Auditoría' },
    { name: 'Comentarios', label: 'COMENTARIOS', type: 'LongText', section: 'Comentarios' },
    {
      name: 'Calendario',
      type: 'Enum',
      origin: 'migration',
      hidden: true,
      values: ['Personal', 'Empresarial'],
      defaultValue: () => 'Empresarial',
    },
    { name: '_calendarOwnerUuid', type: 'Text', origin: 'system', hidden: true, readOnly: true },
    { name: 'Etapa_actual', type: 'Text', origin: 'system', virtual: true, hidden: true, readOnly: true },
  ],
})
