import {
  activeCustomerStatuses,
  crmActions,
  crmCustomerTypes,
  crmResponsibles,
  prospectStatuses,
} from '@/schema/catalogs'
import { refValue } from '@/schema/formulas'
import { defineTable, migrationRef } from '@/schema/helpers'

export const gestionClientesTable = defineTable({
  name: 'Gestion Clientes',
  displayName: 'Seguimiento Clientes',
  sheet: 'Gestion Clientes',
  label: 'Id_CRM',
  legacyBusinessKey: 'Id_CRM',
  permissionView: 'Gestion Clientes',
  module: 'CRM',
  icon: 'Handshake',
  description: 'Bitácora de prospección y seguimiento comercial.',
  defaultView: 'dashboard',
  columns: [
    migrationRef('cliente_uuid', 'Cliente interno', 'CLIENTES'),
    {
      name: 'Id_CRM',
      label: 'Consecutivo CRM',
      type: 'Text',
      labelColumn: true,
      required: true,
      readOnly: true,
      description: 'Se asigna automáticamente al crear el registro.',
    },
    { name: 'Fecha_contacto', type: 'Date', required: true },
    {
      name: 'Nombre_empresa',
      type: 'Ref',
      required: true,
      ref: { table: 'CLIENTES', keyColumn: '_uuid' },
      syncTo: 'cliente_uuid',
    },
    { name: 'Pagina_empresa', type: 'Url' },
    {
      name: 'Contacto',
      type: 'Text',
      readOnly: true,
      formula: (row, context) => refValue(row, 'cliente_uuid', 'CLIENTES', 'CONTACTO', context),
    },
    {
      name: 'Telefono',
      type: 'Phone',
      readOnly: true,
      formula: (row, context) =>
        refValue(row, 'cliente_uuid', 'CLIENTES', 'TELEFONO CONTACTO', context),
    },
    {
      name: 'Email',
      type: 'Email',
      readOnly: true,
      formula: (row, context) => refValue(row, 'cliente_uuid', 'CLIENTES', 'EMAIL', context),
    },
    { name: 'Tipo_cliente', type: 'Enum', values: crmCustomerTypes },
    { name: 'Accion', type: 'Enum', values: crmActions },
    {
      name: 'Responsable',
      label: 'Responsables',
      type: 'EnumList',
      required: true,
      values: crmResponsibles,
      description: 'Selecciona uno o varios responsables del seguimiento.',
    },
    {
      name: 'Estatus_prospeccion',
      type: 'Enum',
      values: prospectStatuses,
      showIf: (row) => row['Tipo_cliente'] === '🔵Prospecto',
      description: 'Al seleccionar ✅Cliente, la empresa se convierte automáticamente y deja de aparecer como prospecto.',
    },
    {
      name: 'Estatus_cliente',
      type: 'Enum',
      values: activeCustomerStatuses,
      showIf: (row) => row['Tipo_cliente'] === '🟢Activo',
    },
    { name: 'Notas', type: 'Text' },
    {
      name: 'Calendario',
      label: 'Guardar evento en',
      type: 'Enum',
      origin: 'migration',
      required: true,
      values: ['Personal', 'Empresarial'],
      section: 'Calendario',
      description: 'Personal solo es visible para tu cuenta; Empresarial es visible para el equipo.',
      defaultValue: () => 'Personal',
    },
    {
      name: '_calendarOwnerUuid',
      label: 'Propietario del calendario',
      type: 'Text',
      origin: 'system',
      hidden: true,
      readOnly: true,
    },
    {
      name: 'Etapa_actual',
      label: 'Etapa actual de la empresa',
      type: 'Text',
      origin: 'system',
      virtual: true,
      hidden: true,
      readOnly: true,
    },
  ],
})
