import {
  activeCustomerStatuses,
  crmActions,
  crmContactOrigins,
  crmContactTypes,
  crmCustomerTypes,
  crmResponsibles,
  prospectStatuses,
} from '@/schema/catalogs'
import { defineTable, migrationRef } from '@/schema/helpers'

export const gestionClientesTable = defineTable({
  name: 'Gestion Clientes',
  displayName: 'Seguimiento Clientes',
  sheet: 'Gestion Clientes',
  label: 'ID',
  legacyBusinessKey: 'Id_CRM',
  permissionView: 'Gestion Clientes',
  module: 'CRM',
  icon: 'Handshake',
  description: 'Directorio profesional de contactos y seguimiento comercial.',
  defaultView: 'dashboard',
  columns: [
    migrationRef('cliente_uuid', 'Cliente interno', 'CLIENTES'),

    // Campos históricos conservados para compatibilidad con el calendario,
    // comunicaciones y ciclo comercial de los registros existentes.
    { name: 'Id_CRM', type: 'Text', required: true, readOnly: true, hidden: true },
    { name: 'Fecha_contacto', type: 'Date', hidden: true },
    { name: 'Nombre_empresa', type: 'Text', hidden: true },
    { name: 'Pagina_empresa', type: 'Url', hidden: true },
    { name: 'Contacto', type: 'Text', hidden: true },
    { name: 'Telefono', type: 'Phone', hidden: true },
    { name: 'Email', type: 'Email', hidden: true },
    { name: 'Tipo_cliente', type: 'Enum', values: crmCustomerTypes, hidden: true },
    { name: 'Accion', type: 'Enum', values: crmActions, hidden: true },
    {
      name: 'Responsable',
      type: 'EnumList',
      required: true,
      values: crmResponsibles,
      section: 'Información profesional',
      description: 'Selecciona uno o varios responsables del contacto.',
    },
    { name: 'Estatus_prospeccion', type: 'Enum', values: prospectStatuses, hidden: true },
    { name: 'Estatus_cliente', type: 'Enum', values: activeCustomerStatuses, hidden: true },
    { name: 'Notas', type: 'LongText', hidden: true },

    // Nueva ficha profesional. Estas columnas se agregan y rellenan sin borrar
    // las columnas originales de la hoja.
    {
      name: 'ID',
      type: 'Text',
      labelColumn: true,
      required: true,
      readOnly: true,
      origin: 'migration',
      section: 'Información profesional',
      description: 'Consecutivo automático con formato GC-0001.',
    },
    { name: 'Nombre', type: 'Name', required: true, origin: 'migration', section: 'Información profesional' },
    { name: 'Apellido', type: 'Name', origin: 'migration', hidden: true },
    { name: 'Segundo Nombre', type: 'Name', origin: 'migration', hidden: true },
    { name: 'Cargo', type: 'Text', origin: 'migration', section: 'Información profesional' },
    { name: 'Compañía', type: 'Text', required: true, origin: 'migration', section: 'Información profesional' },
    {
      name: 'Tipo de Contacto',
      type: 'Enum',
      required: true,
      values: crmContactTypes,
      origin: 'migration',
      section: 'Información profesional',
      defaultValue: () => 'Prospecto',
    },
    { name: 'Teléfono del trabajo', type: 'Phone', origin: 'migration', section: 'Datos de contacto' },
    { name: 'Móvil', type: 'Phone', origin: 'migration', section: 'Datos de contacto' },
    { name: 'Otro número de teléfono', type: 'Phone', origin: 'migration', hidden: true },
    { name: 'Sitio web Corporativo', type: 'Url', origin: 'migration', section: 'Datos de contacto' },
    { name: 'E-mail del trabajo', type: 'Email', origin: 'migration', section: 'Datos de contacto' },
    { name: 'Última actualización en', type: 'DateTime', readOnly: true, origin: 'migration', section: 'Auditoría' },
    {
      name: 'Origen',
      type: 'Enum',
      values: crmContactOrigins,
      origin: 'migration',
      section: 'Procedencia',
      defaultValue: () => 'Prospección',
    },
    { name: 'Información de origen', type: 'Text', origin: 'migration', section: 'Procedencia' },
    {
      name: 'Incluido en la exportación',
      type: 'Bool',
      origin: 'migration',
      hidden: true,
      defaultValue: () => false,
    },
    { name: 'Creado por', type: 'Text', readOnly: true, origin: 'migration', section: 'Auditoría' },
    { name: 'Creado', type: 'DateTime', readOnly: true, origin: 'migration', section: 'Auditoría' },
    { name: 'Modificado por', type: 'Text', readOnly: true, origin: 'migration', section: 'Auditoría' },
    { name: 'Modificado', type: 'DateTime', readOnly: true, origin: 'migration', section: 'Auditoría' },
    { name: 'Comentarios', type: 'LongText', origin: 'migration', section: 'Comentarios' },
    {
      name: 'Calendario',
      type: 'Enum',
      origin: 'migration',
      hidden: true,
      values: ['Personal', 'Empresarial'],
      defaultValue: () => 'Empresarial',
    },
    { name: '_calendarOwnerUuid', type: 'Text', origin: 'system', hidden: true, readOnly: true },
    { name: 'Etapa_actual', type: 'Text', origin: 'system', virtual: true, hidden: true, readOnly: true },
  ],
})
