import { defineTable, namedColumns } from '@/schema/helpers'

export const matrizDispositivosTable = defineTable({
  name: 'MATRIZ DISPOSITIVOS',
  sheet: 'MATRIZ DISPOSITIVOS',
  label: 'Modelo',
  legacyBusinessKey: 'Modelo',
  permissionView: 'Matriz Dispositivos',
  module: 'Catálogo técnico',
  icon: 'Cpu',
  description: 'Fichas técnicas y comparador de dispositivos GPS.',
  defaultView: 'card',
  columns: [
    { name: 'Modelo', type: 'Text', labelColumn: true, required: true },
    { name: 'Marca', type: 'Text' },
    { name: 'Imagen', type: 'Image' },
    ...namedColumns([
      'Familia',
      'Tipo',
      'Red',
      'BLE',
      'IP',
      'Agua_exterior',
      'Ambiente',
      'Dimensiones',
    ]),
    { name: 'Peso_g', type: 'Number' },
    { name: 'Bateria(miliamperios)', type: 'Number' },
    ...namedColumns([
      'Voltaje',
      'Temp_operacion',
      'Temp_almacenamiento',
      'Montaje_instalacion',
      'DI',
      'DO',
      'AI_Config',
      'RS232',
      'RS485',
      'CAN',
      'One_Wire',
      'RFID',
      'OBD',
      'WiFi',
      'USB_Config',
      'Carga_transmision_datos',
      'Antena_red_GNSS',
      'Indicador_LED',
      'Interruptor_fisico',
      'Output_5V_12V',
      'BLE_accessory_support',
      'Sensor_temp',
      'Sensor_luz_hall',
      'Acelerometro',
      'Geocercas',
      'FOTA',
      'Protocolos',
      'Seguridad',
      'Uso_recomendado',
      'Comentario',
    ]),
    { name: 'Frecuencia_reporte (min)', type: 'Number' },
    { name: 'Calculadora_bateria', type: 'Number' },
    { name: 'Ficha_Tecnica', type: 'Url' },
  ],
})
