import {
  supportAgents,
  supportCaseTypes,
  supportChannels,
  supportStatuses,
  ticketCustomerTypes,
  ticketOwners,
} from '@/schema/catalogs'
import { defineTable } from '@/schema/helpers'

export const ticketSoporteTable = defineTable({
  name: 'Ticket Soporte',
  sheet: 'Ticket Soporte',
  label: 'FOLIO',
  legacyBusinessKey: '_ComputedKey',
  permissionView: 'Ticket Soporte',
  module: 'Soporte',
  icon: 'LifeBuoy',
  description: 'Registro y seguimiento de solicitudes de soporte.',
  defaultView: 'table',
  columns: [
    {
      name: 'FOLIO',
      type: 'Text',
      labelColumn: true,
      readOnly: true,
      origin: 'migration',
      description: 'Folio autoritativo TS-AAAA-NNNN.',
    },
    { name: '🗓️Fecha Registro', type: 'Date', required: true },
    { name: '🏭Cliente', type: 'Text', required: true },
    { name: '⭐Tipo de Cliente', type: 'Enum', values: ticketCustomerTypes },
    { name: '🧾Cuenta propietaria', type: 'Enum', values: ticketOwners },
    { name: '🧑Contacto', type: 'Text' },
    { name: '📞Teléfono', type: 'Phone', required: true },
    { name: '✉️Email', type: 'Email' },
    { name: '💼Asesor de Ventas', type: 'Text' },
    { name: '🎫Canal de  Atención', type: 'EnumList', values: supportChannels },
    { name: '📌Tipo de Caso', type: 'Enum', values: supportCaseTypes },
    { name: '🔎Descripción del problema', type: 'LongText' },
    { name: '🧑Atendió', type: 'Enum', values: supportAgents },
    { name: '🛡️Comentarios Soporte', type: 'LongText' },
    { name: '🚦Estatus', type: 'Enum', values: supportStatuses },
    {
      name: '_ComputedKey',
      type: 'Text',
      required: true,
      virtual: true,
      hidden: true,
      readOnly: true,
      description: 'Clave heredada; deja de utilizarse como identificador.',
    },
  ],
})
