import { defineTable, migrationRef } from '@/schema/helpers'

export const usuariosTable = defineTable({
  name: 'Usuarios',
  sheet: 'Usuarios',
  label: 'UserName',
  legacyBusinessKey: 'UserID',
  permissionView: 'Usuarios',
  module: 'Administración',
  icon: 'Users',
  description: 'Usuarios autorizados y su perfil.',
  defaultView: 'table',
  columns: [
    migrationRef('perfil_uuid', 'Perfil interno', 'Perfiles'),
    { name: 'UserID', type: 'Text', required: true },
    { name: 'UserName', type: 'Name', labelColumn: true },
    { name: 'UserEmail', type: 'Email', required: true },
    {
      name: 'UserRole',
      type: 'Ref',
      ref: { table: 'Perfiles', keyColumn: '_uuid' },
      syncTo: 'perfil_uuid',
    },
    {
      name: 'UserActive',
      type: 'Bool',
      required: true,
      description: 'Normalizado desde TRUE/true/VERDADERO/SI/1.',
    },
    {
      name: 'PasswordHash',
      type: 'Text',
      origin: 'migration',
      hidden: true,
      readOnly: true,
      sensitive: true,
    },
    {
      name: 'PasswordUpdatedAt',
      type: 'DateTime',
      origin: 'migration',
      hidden: true,
      readOnly: true,
      sensitive: true,
    },
    {
      name: 'MustChangePassword',
      type: 'Bool',
      origin: 'migration',
      hidden: true,
      readOnly: true,
      sensitive: true,
    },
    {
      name: 'FailedAttempts',
      type: 'Number',
      origin: 'migration',
      hidden: true,
      readOnly: true,
      sensitive: true,
    },
    {
      name: 'LockedUntil',
      type: 'DateTime',
      origin: 'migration',
      hidden: true,
      readOnly: true,
      sensitive: true,
    },
    {
      name: 'LastLoginAt',
      type: 'DateTime',
      origin: 'migration',
      hidden: true,
      readOnly: true,
      sensitive: true,
    },
    {
      name: 'SessionVersion',
      type: 'Number',
      origin: 'migration',
      hidden: true,
      readOnly: true,
      sensitive: true,
    },
  ],
})
