/**
 * ARCHIVO GENERADO. No editar manualmente.
 * Fuente: src/schema mediante npm run gas:generate-schema.
 */
var TRAIOT_SCHEMA_TABLES = Object.freeze([
  {
    "name": "ALMACEN",
    "sheet": "ALMACEN",
    "sourceHeaders": [
      "No. Item",
      "ID PRODUCTO",
      "IMAGEN",
      "PROVEEDOR",
      "NOMBRE",
      "UNIDAD DE MEDIDA",
      "UNIDAD DE MEDIDA SAT",
      "KIT INSTALACION",
      "MONEDA",
      "TIPO DE CAMBIO",
      "COSTO",
      "MANO DE OBRA",
      "PRECIO VENTA PARA ASESOR",
      "STOCK MINIMO",
      "STOCK MAXIMO",
      "AVISO DE COMPRA",
      "MTS. CABLE INCLUIDOS",
      "CATEGORIA",
      "CRITICO",
      "CENTRO DE COSTOS",
      "TIEMPO DE ENTREGA",
      "CLAVE SAT",
      "ESTATUS",
      "COMPRAS",
      "PEDIDOS",
      "STOCK"
    ],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "proveedor_uuid",
      "No. Item",
      "ID PRODUCTO",
      "IMAGEN",
      "PROVEEDOR",
      "NOMBRE",
      "UNIDAD DE MEDIDA",
      "UNIDAD DE MEDIDA SAT",
      "KIT INSTALACION",
      "MONEDA",
      "TIPO DE CAMBIO",
      "COSTO",
      "MANO DE OBRA",
      "PRECIO VENTA PARA ASESOR",
      "STOCK MINIMO",
      "STOCK MAXIMO",
      "AVISO DE COMPRA",
      "MTS. CABLE INCLUIDOS",
      "CATEGORIA",
      "CRITICO",
      "CENTRO DE COSTOS",
      "TIEMPO DE ENTREGA",
      "CLAVE SAT",
      "ESTATUS",
      "COMPRAS",
      "PEDIDOS",
      "STOCK"
    ],
    "newTable": false
  },
  {
    "name": "COMPRAS",
    "sheet": "COMPRAS",
    "sourceHeaders": [
      "FECHA COMPRA",
      "ID COMPRA",
      "ID PRODUCTO",
      "NOMBRE",
      "PROVEEDOR",
      "COSTO",
      "KIT INSTALACION",
      "CANTIDAD",
      "SUBTOTAL",
      "COSTO DE ENVIO",
      "PRECIO DE COMPRA",
      "ESTATUS COMPRA",
      "COMENTARIOS",
      "VALIDADOR COMPRA"
    ],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "producto_uuid",
      "FECHA COMPRA",
      "ID COMPRA",
      "ID PRODUCTO",
      "NOMBRE",
      "PROVEEDOR",
      "COSTO",
      "KIT INSTALACION",
      "CANTIDAD",
      "SUBTOTAL",
      "COSTO DE ENVIO",
      "PRECIO DE COMPRA",
      "ESTATUS COMPRA",
      "COMENTARIOS",
      "VALIDADOR COMPRA"
    ],
    "newTable": false
  },
  {
    "name": "PEDIDOS",
    "sheet": "PEDIDOS",
    "sourceHeaders": [
      "FECHA",
      "TIPO DE PEDIDO",
      "ID PEDIDO",
      "ID PRODUCTO",
      "NOMBRE",
      "CATEGORIA",
      "PRECIO VENTA PARA ASESOR",
      "EQUIPOS A VENDER",
      "COSTO INSTALACION",
      "ENVIO",
      "SUBTOTAL",
      "IVA",
      "TOTAL",
      "TIPO CLIENTE",
      "RAZON SOCIAL",
      "ID CLIENTE",
      "DIRECCION",
      "TELEFONO",
      "EMAIL",
      "UBICACION",
      "CONTACTO",
      "TELEFONO CONTACTO",
      "ESTATUS PEDIDO",
      "COMENTARIOS",
      "VALIDADOR VENTA"
    ],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "producto_uuid",
      "cliente_uuid",
      "FECHA",
      "TIPO DE PEDIDO",
      "ID PEDIDO",
      "ID PRODUCTO",
      "NOMBRE",
      "CATEGORIA",
      "PRECIO VENTA PARA ASESOR",
      "EQUIPOS A VENDER",
      "COSTO INSTALACION",
      "ENVIO",
      "SUBTOTAL",
      "IVA",
      "TOTAL",
      "TIPO CLIENTE",
      "RAZON SOCIAL",
      "ID CLIENTE",
      "DIRECCION",
      "TELEFONO",
      "EMAIL",
      "UBICACION",
      "CONTACTO",
      "TELEFONO CONTACTO",
      "ESTATUS PEDIDO",
      "COMENTARIOS",
      "VALIDADOR VENTA"
    ],
    "newTable": false
  },
  {
    "name": "PROVEEDORES",
    "sheet": "PROVEEDORES",
    "sourceHeaders": [
      "ID",
      "RAZON_SOCIAL",
      "RFC",
      "CALLE",
      "NO_INT",
      "NO_EXT",
      "COLONIA",
      "CP",
      "MUNICIPIO",
      "CIUDAD",
      "ESTADO",
      "PAIS",
      "TELEFONO",
      "TELEFONO2",
      "TELEFONO3",
      "TELEFONO4",
      "CORREO_E",
      "WEB",
      "DIAS_PRONTO_PAGO",
      "DIAS_PLAZO",
      "DECUENTO_PRONTO",
      "CONTACTO",
      "CONDICION_PAGO",
      "TIPO",
      "INCOTERM",
      "EXISTE"
    ],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "ID",
      "RAZON_SOCIAL",
      "RFC",
      "CALLE",
      "NO_INT",
      "NO_EXT",
      "COLONIA",
      "CP",
      "MUNICIPIO",
      "CIUDAD",
      "ESTADO",
      "PAIS",
      "TELEFONO",
      "TELEFONO2",
      "TELEFONO3",
      "TELEFONO4",
      "CORREO_E",
      "WEB",
      "DIAS_PRONTO_PAGO",
      "DIAS_PLAZO",
      "DECUENTO_PRONTO",
      "CONTACTO",
      "CONDICION_PAGO",
      "TIPO",
      "INCOTERM",
      "EXISTE"
    ],
    "newTable": false
  },
  {
    "name": "CLIENTES",
    "sheet": "CLIENTES",
    "sourceHeaders": [
      "ID CLIENTE",
      "RAZON SOCIAL",
      "DIRECCION",
      "TELEFONO",
      "EMAIL",
      "UBICACION",
      "CONTACTO",
      "TELEFONO CONTACTO",
      "IMAGEN",
      "ESTATUS"
    ],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "ID CLIENTE",
      "RAZON SOCIAL",
      "DIRECCION",
      "TELEFONO",
      "EMAIL",
      "UBICACION",
      "CONTACTO",
      "TELEFONO CONTACTO",
      "IMAGEN",
      "ESTATUS"
    ],
    "newTable": false
  },
  {
    "name": "Gestion Clientes",
    "sheet": "Gestion Clientes",
    "sourceHeaders": [
      "Id_CRM",
      "Fecha_contacto",
      "Nombre_empresa",
      "Pagina_empresa",
      "Contacto",
      "Telefono",
      "Email",
      "Tipo_cliente",
      "Accion",
      "Responsable",
      "Estatus_prospeccion",
      "Estatus_cliente",
      "Notas"
    ],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "cliente_uuid",
      "Id_CRM",
      "Fecha_contacto",
      "Nombre_empresa",
      "Pagina_empresa",
      "Contacto",
      "Telefono",
      "Email",
      "Tipo_cliente",
      "Accion",
      "Responsable",
      "Estatus_prospeccion",
      "Estatus_cliente",
      "Notas"
    ],
    "newTable": false
  },
  {
    "name": "Ticket Soporte",
    "sheet": "Ticket Soporte",
    "sourceHeaders": [
      "🗓️Fecha Registro",
      "🏭Cliente",
      "⭐Tipo de Cliente",
      "🧾Cuenta propietaria",
      "🧑Contacto",
      "📞Teléfono",
      "✉️Email",
      "💼Asesor de Ventas",
      "🎫Canal de \nAtención",
      "📌Tipo de Caso",
      "🔎Descripción del problema",
      "🧑Atendió",
      "🛡️Comentarios Soporte",
      "🚦Estatus"
    ],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "FOLIO",
      "🗓️Fecha Registro",
      "🏭Cliente",
      "⭐Tipo de Cliente",
      "🧾Cuenta propietaria",
      "🧑Contacto",
      "📞Teléfono",
      "✉️Email",
      "💼Asesor de Ventas",
      "🎫Canal de \nAtención",
      "📌Tipo de Caso",
      "🔎Descripción del problema",
      "🧑Atendió",
      "🛡️Comentarios Soporte",
      "🚦Estatus"
    ],
    "newTable": false
  },
  {
    "name": "INSTALACIONES",
    "sheet": "INSTALACIONES",
    "sourceHeaders": [
      "FOLIO SERVICIO",
      "FECHA",
      "MES",
      "AÑO EN CURSO",
      "CLIENTE",
      "CONSULTOR VENTAS",
      "TIPO DE SERVICIO",
      "ESTATUS",
      "TECNICO",
      "SOLUCION",
      "MARCA DISPOSITIVO",
      "MODELO DISPOSITIVO",
      "IMEI",
      "SIM",
      "PROVEEDOR SIM",
      "CONTACTO",
      "TELEFONO",
      "EMAIL",
      "DIRECCION",
      "UBICACION",
      "ECONOMICO",
      "ACCESORIOS ADICIONALES",
      "CEREBRO",
      "PANICO",
      "CORTE",
      "NO. TANQUES",
      "TANQUE 1 (MARCA)",
      "TANQUE 1 (SERIE)",
      "TANQUE 2 (MARCA)",
      "TANQUE 2 (SERIE)",
      "TANQUE 3 (MARCA)",
      "TANQUE 3 (SERIE)",
      "IMAGEN FUEL 1",
      "IMAGEN FUEL 2",
      "IMAGEN FUEL 3",
      "IMAGEN FUEL 4",
      "IMAGEN FUEL 5",
      "IMAGEN FUEL 6",
      "IMAGEN FUEL 7",
      "IMAGEN FUEL 8",
      "IMAGEN FUEL 9",
      "IMAGEN FUEL 10",
      "NOTAS COMBUSTIBLE",
      "MARCA AUTO",
      "SUBMARCA",
      "COLOR",
      "AÑO",
      "VIN",
      "PLACAS",
      "ODOMETRO",
      "IMAGEN 1",
      "IMAGEN 2",
      "IMAGEN 3",
      "IMAGEN 4",
      "IMAGEN 5",
      "IMAGEN 6",
      "IMAGEN 7",
      "IMAGEN 8",
      "IMAGEN 9",
      "IMAGEN 10",
      "COMENTARIOS TECNICO",
      "LUCES",
      "DIRECCIONALES",
      "INTERMITENTES",
      "CUARTOS",
      "TABLERO",
      "ESTEREO",
      "VIDRIOS ELECTRICOS",
      "AIRE ACONDICIONADO",
      "SEGUROS ELECTRICOS",
      "BATERIA",
      "CLAXON",
      "LUZ INTERIOR",
      "VISERAS",
      "IMAGEN CHECK 1",
      "IMAGEN CHECK 2",
      "IMAGEN CHECK 3",
      "IMAGEN CHECK 4",
      "IMAGEN CHECK 5",
      "CHECKLIST OBSERVACIONES",
      "POSICIONAMIENTO OK",
      "OBSERVACIONES 1",
      "IGNICION",
      "OBSERVACIONES 2",
      "PRUEBA BLOQUEO/HABILITADO DE MOTOR",
      "OBSERVACIONES 3",
      "DESCONEXION BATERIA",
      "OBSERVACIONES 4",
      "BOTON SOS",
      "OBSERVACIONES 5",
      "NOMBRE DE QUIEN RECIBE",
      "FIRMA DE QUIEN RECIBE",
      "IMAGEN INE"
    ],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "cliente_uuid",
      "tecnico_uuid",
      "consultor_uuid",
      "dispositivo_uuid",
      "FOLIO SERVICIO",
      "FECHA",
      "MES",
      "AÑO EN CURSO",
      "CLIENTE",
      "CONSULTOR VENTAS",
      "TIPO DE SERVICIO",
      "ESTATUS",
      "TECNICO",
      "SOLUCION",
      "MARCA DISPOSITIVO",
      "MODELO DISPOSITIVO",
      "IMEI",
      "SIM",
      "PROVEEDOR SIM",
      "CONTACTO",
      "TELEFONO",
      "EMAIL",
      "DIRECCION",
      "UBICACION",
      "ECONOMICO",
      "ACCESORIOS ADICIONALES",
      "CEREBRO",
      "PANICO",
      "CORTE",
      "NO. TANQUES",
      "TANQUE 1 (MARCA)",
      "TANQUE 1 (SERIE)",
      "TANQUE 2 (MARCA)",
      "TANQUE 2 (SERIE)",
      "TANQUE 3 (MARCA)",
      "TANQUE 3 (SERIE)",
      "IMAGEN FUEL 1",
      "IMAGEN FUEL 2",
      "IMAGEN FUEL 3",
      "IMAGEN FUEL 4",
      "IMAGEN FUEL 5",
      "IMAGEN FUEL 6",
      "IMAGEN FUEL 7",
      "IMAGEN FUEL 8",
      "IMAGEN FUEL 9",
      "IMAGEN FUEL 10",
      "NOTAS COMBUSTIBLE",
      "MARCA AUTO",
      "SUBMARCA",
      "COLOR",
      "AÑO",
      "VIN",
      "PLACAS",
      "ODOMETRO",
      "IMAGEN 1",
      "IMAGEN 2",
      "IMAGEN 3",
      "IMAGEN 4",
      "IMAGEN 5",
      "IMAGEN 6",
      "IMAGEN 7",
      "IMAGEN 8",
      "IMAGEN 9",
      "IMAGEN 10",
      "COMENTARIOS TECNICO",
      "LUCES",
      "DIRECCIONALES",
      "INTERMITENTES",
      "CUARTOS",
      "TABLERO",
      "ESTEREO",
      "VIDRIOS ELECTRICOS",
      "AIRE ACONDICIONADO",
      "SEGUROS ELECTRICOS",
      "BATERIA",
      "CLAXON",
      "LUZ INTERIOR",
      "VISERAS",
      "IMAGEN CHECK 1",
      "IMAGEN CHECK 2",
      "IMAGEN CHECK 3",
      "IMAGEN CHECK 4",
      "IMAGEN CHECK 5",
      "CHECKLIST OBSERVACIONES",
      "POSICIONAMIENTO OK",
      "OBSERVACIONES 1",
      "IGNICION",
      "OBSERVACIONES 2",
      "PRUEBA BLOQUEO/HABILITADO DE MOTOR",
      "OBSERVACIONES 3",
      "DESCONEXION BATERIA",
      "OBSERVACIONES 4",
      "BOTON SOS",
      "OBSERVACIONES 5",
      "NOMBRE DE QUIEN RECIBE",
      "FIRMA DE QUIEN RECIBE",
      "IMAGEN INE"
    ],
    "newTable": false
  },
  {
    "name": "instalacion_fotos",
    "sheet": "instalacion_fotos",
    "sourceHeaders": [],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "instalacion_uuid",
      "categoria",
      "orden",
      "driveFileId",
      "nota"
    ],
    "newTable": true
  },
  {
    "name": "instalacion_tanques",
    "sheet": "instalacion_tanques",
    "sourceHeaders": [],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "instalacion_uuid",
      "orden",
      "marca",
      "serie"
    ],
    "newTable": true
  },
  {
    "name": "instalacion_checklist",
    "sheet": "instalacion_checklist",
    "sourceHeaders": [],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "instalacion_uuid",
      "punto",
      "resultado",
      "observacion"
    ],
    "newTable": true
  },
  {
    "name": "Laboratorio",
    "sheet": "Laboratorio",
    "sourceHeaders": [
      "FOLIO",
      "FECHA ENTRADA",
      "PROBLEMA DETECTADO",
      "ESTATUS",
      "MARCA",
      "MODELO",
      "IMEI",
      "TEL SIM",
      "CLIENTE",
      "REVISADO POR",
      "PRUEBAS REALIZADAS",
      "FECHA SALIDA",
      "NOTAS DE REVISION",
      "IMAGEN 1",
      "NOTAS IMAGEN 1",
      "IMAGEN 2",
      "NOTAS IMAGEN 2",
      "IMAGEN 3",
      "NOTAS IMAGEN 3",
      "IMAGEN 4",
      "NOTAS IMAGEN 4",
      "IMAGEN 5",
      "NOTAS IMAGEN 5",
      "DIAS LABORATORIO",
      "SEMAFORO"
    ],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "cliente_uuid",
      "FOLIO",
      "FECHA ENTRADA",
      "PROBLEMA DETECTADO",
      "ESTATUS",
      "MARCA",
      "MODELO",
      "IMEI",
      "TEL SIM",
      "CLIENTE",
      "REVISADO POR",
      "PRUEBAS REALIZADAS",
      "FECHA SALIDA",
      "NOTAS DE REVISION",
      "IMAGEN 1",
      "NOTAS IMAGEN 1",
      "IMAGEN 2",
      "NOTAS IMAGEN 2",
      "IMAGEN 3",
      "NOTAS IMAGEN 3",
      "IMAGEN 4",
      "NOTAS IMAGEN 4",
      "IMAGEN 5",
      "NOTAS IMAGEN 5",
      "DIAS LABORATORIO",
      "SEMAFORO"
    ],
    "newTable": false
  },
  {
    "name": "MATRIZ DISPOSITIVOS",
    "sheet": "MATRIZ DISPOSITIVOS",
    "sourceHeaders": [
      "Modelo",
      "Marca",
      "Imagen",
      "Familia",
      "Tipo",
      "Red",
      "BLE",
      "IP",
      "Agua_exterior",
      "Ambiente",
      "Dimensiones",
      "Peso_g",
      "Bateria(miliamperios)",
      "Voltaje",
      "Temp_operacion",
      "Temp_almacenamiento",
      "Montaje_instalacion",
      "DI",
      "DO",
      "AI_Config",
      "RS232",
      "RS485",
      "CAN",
      "One_Wire",
      "RFID",
      "OBD",
      "WiFi",
      "USB_Config",
      "Carga_transmision_datos",
      "Antena_red_GNSS",
      "Indicador_LED",
      "Interruptor_fisico",
      "Output_5V_12V",
      "BLE_accessory_support",
      "Sensor_temp",
      "Sensor_luz_hall",
      "Acelerometro",
      "Geocercas",
      "FOTA",
      "Protocolos",
      "Seguridad",
      "Uso_recomendado",
      "Comentario",
      "Frecuencia_reporte (min)",
      "Calculadora_bateria",
      "Ficha_Tecnica"
    ],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "Modelo",
      "Marca",
      "Imagen",
      "Familia",
      "Tipo",
      "Red",
      "BLE",
      "IP",
      "Agua_exterior",
      "Ambiente",
      "Dimensiones",
      "Peso_g",
      "Bateria(miliamperios)",
      "Voltaje",
      "Temp_operacion",
      "Temp_almacenamiento",
      "Montaje_instalacion",
      "DI",
      "DO",
      "AI_Config",
      "RS232",
      "RS485",
      "CAN",
      "One_Wire",
      "RFID",
      "OBD",
      "WiFi",
      "USB_Config",
      "Carga_transmision_datos",
      "Antena_red_GNSS",
      "Indicador_LED",
      "Interruptor_fisico",
      "Output_5V_12V",
      "BLE_accessory_support",
      "Sensor_temp",
      "Sensor_luz_hall",
      "Acelerometro",
      "Geocercas",
      "FOTA",
      "Protocolos",
      "Seguridad",
      "Uso_recomendado",
      "Comentario",
      "Frecuencia_reporte (min)",
      "Calculadora_bateria",
      "Ficha_Tecnica"
    ],
    "newTable": false
  },
  {
    "name": "Usuarios",
    "sheet": "Usuarios",
    "sourceHeaders": [
      "UserID",
      "UserName",
      "UserEmail",
      "UserRole",
      "UserActive"
    ],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "perfil_uuid",
      "UserID",
      "UserName",
      "UserEmail",
      "UserRole",
      "UserActive"
    ],
    "newTable": false
  },
  {
    "name": "Perfiles",
    "sheet": "Perfiles",
    "sourceHeaders": [
      "PerfilID",
      "VistasPermitidas"
    ],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "PerfilID",
      "VistasPermitidas"
    ],
    "newTable": false
  },
  {
    "name": "Menu",
    "sheet": "Menu",
    "sourceHeaders": [
      "IdMenu",
      "NombreMenu",
      "VistaMenu",
      "ImagenMenu"
    ],
    "targetHeaders": [
      "_uuid",
      "_updatedAt",
      "_deleted",
      "IdMenu",
      "NombreMenu",
      "VistaMenu",
      "ImagenMenu"
    ],
    "newTable": false
  }
]);
